services:
  app1:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  app2:
    build: 
      context: ./web01
      dockerfile: Dockerfile
    ports:
      - "81:80"
  dns: 
    build:
      context: ./dns
      dockerfile: Dockerfile
    ports:
    - "53:53/udp"
    - "53:53/tcp"


